version: '3.8'
services:

  webserver:
# Musialem dodać aby pliki byly poprawnie synchronizowane między kontenerem a windowsem
    volumes:
      - ./:/var/www/html/
    build:
      context: .
      dockerfile: Dockerfile
    container_name: recruitment-webserver
    restart: unless-stopped
    ports:
      - "80:80"
    environment:
      - APACHE_RUN_USER=www-data
      - APACHE_RUN_GROUP=www-data
      - APACHE_DOCUMENT_ROOT=/var/www/html/public